export default class Beasts {
    allBeasts() {
        this.beasts = allBeasts()
    }
    fire() {
        this.beasts = fireBeasts()
    }

    water() {
        this.beasts = waterBeasts()
    }

    air() {
        this.beasts = airBeasts()
    }

    earth() {
        this.beasts = earthBeasts()
    }

    wizard() {
        this.beasts = wizard()
    }

    animal() {
        this.beasts = animalBeasts()
    }

}

class Beast {
    constructor(name, image, elemental) {
        this.name = name
        this.image = image
        this.elemental = elemental
    }
}

function fireBeasts() {
    return [
        new Beast("Cornix",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/cornix.png?raw=true",
        "FIRE"),
        new Beast("Doomskull",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/doomskull.png?raw=true",
        "FIRE"),   
        new Beast("Epos",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/epos.png?raw=true",
        "FIRE"),    
        new Beast("Ferno",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/ferno.png?raw=true",
        "FIRE"), 
        new Beast("Flaymar",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/flaymar.png?raw=true",
        "FIRE"),
        new Beast("Hellion",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/hellion.png?raw=true",
        "FIRE"),
        new Beast("Koba",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/koba.png?raw=true",
        "FIRE"),    
        new Beast("Murk",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/murk.png?raw=true",
        "FIRE")
    ]                                                                                                                                                                                       
}

function waterBeasts() {
    return [
        new Beast("Elko",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/elko.png?raw=true",
        "WATER"),
        new Beast("Nixa",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/nixa.png?raw=true",
        "WATER"),
        new Beast("Ellik",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/ellik.png?raw=true",
        "WATER"),
        new Beast("Blaze",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/blaze.png?raw=true",
        "WATER"),
        new Beast("Marlik",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/marlik.png?raw=true",
        "WATER"),
        new Beast("Soara",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/soara.png?raw=true",
        "WATER"),
        new Beast("Plexor",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/plexor.png?raw=true",
        "WATER"),
        new Beast("Voltrex",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/voltrex.png?raw=true",
        "WATER"),  
        new Beast("Lustor",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/lustor.png?raw=true",
        "WATER"),
        new Beast("Sepron",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/sepron.png?raw=true",
        "WATER"),
        new Beast("Hecton",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/hecton.png?raw=true",
        "WATER"),
        new Beast("Krabb",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/krabb.png?raw=true",
        "WATER"),
        new Beast("Narga",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/narga.png?raw=true",
        "WATER"), 
        new Beast("Serpio",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/serpio.png?raw=true",
        "WATER"),
        new Beast("Balisk",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/balisk.png?raw=true",
        "WATER"),
        new Beast("Spikefin",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/spikefin.png?raw=true",
        "WATER")       
    ]
}

function airBeasts() {
    return [
        new Beast("Amictus",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/amictus.png?raw=true",
        "AIR"),        
        new Beast("Brutus",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/brutus.png?raw=true",
        "AIR"),
        new Beast("Carnivora",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/carnivora.png?raw=true",
        "AIR"),
        new Beast("Fang",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/fang.png?raw=true",
        "AIR"),    
        new Beast("Falra",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/falra.png?raw=true",
        "AIR"), 
        new Beast("Linka",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/linka.png?raw=true",
        "AIR"),  
        new Beast("Hawkite",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/hawkite.png?raw=true",
        "AIR"),
        new Beast("Koraka",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/koraka.png?raw=true",
        "AIR"),
        new Beast("Kronus",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/kronus.png?raw=true",
        "AIR"),
        new Beast("Soltra",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/soltra.png?raw=true",
        "AIR"),
        new Beast("Torno",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/torno.png?raw=true",
        "AIR"),
        new Beast("Vespick",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/vespick.png?raw=true",
        "AIR"),
        new Beast("Tempest",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/tempest.png?raw=true",
        "AIR"),
        new Beast("Spark",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/spark.png?raw=true",
        "AIR"),
        new Beast("Oradu's Falcon",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/oradu'sfalcon.png?raw=true",
        "AIR")
    ]
}

function earthBeasts() {
    return [
        new Beast("Arcta",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/arcta.png?raw=true",
        "EARTH"),
        new Beast("Kaymon",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/kaymon.png?raw=true",
        "EARTH"),
        new Beast("Krestor",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/krestor.png?raw=true",
        "EARTH"),
        new Beast("Rashouk",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/rashouk.png?raw=true",
        "EARTH"),
        new Beast("Koldo",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/koldo.png?raw=true",
        "EARTH"),
        new Beast("Nanook",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/nanook.png?raw=true",
        "EARTH"),
        new Beast("Rokk",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/rokk.png?raw=true",
        "EARTH"),
        new Beast("Solix",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/solix.png?raw=true",
        "EARTH"),
        new Beast("Sting",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/sting.png?raw=true",
        "EARTH"), 
        new Beast("Tarrok",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/tarrok.png?raw=true",
        "EARTH"),
        new Beast("Tecton",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/tecton.png?raw=true",
        "EARTH"),
        new Beast("Terra",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/terra.png?raw=true",
        "EARTH"),
        new Beast("Trema",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/trema.png?raw=true",
        "EARTH"),
        new Beast("Xerik",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/xerik.png?raw=true",
        "EARTH"),
        new Beast("Piranha Pirate",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/piranhapirate.png?raw=true",
        "EARTH")  
    ]                                                                                                           
}         

function wizard() {
    return [
        new Beast("Malvel",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/malvel.png?raw=true",
        "WIZARD"),
        new Beast("Kensa",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/kensa.png?raw=true",
        "WIZARD"),
        new Beast("Aduro",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/aduro.png?raw=true",
        "WIZARD")
    ]
}

function animalBeasts() {
    return [
        new Beast("Vermock",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/vermock.png?raw=true",
        "ANIMAL"),
        new Beast("Klaxa",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/klaxa.png?raw=true",
        "ANIMAL"),
        new Beast("Tauron",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/tauron.png?raw=true",
        "ANIMAL"),
        new Beast("Torgor",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/torgor.png?raw=true",
        "ANIMAL"),
        new Beast("Torpix",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/torpix.png?raw=true",
        "ANIMAL"),
        new Beast("Trillion",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/trillion.png?raw=true",
        "ANIMAL"),
        new Beast("Skor",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/skor.png?raw=true",
        "ANIMAL"),
        new Beast("Slivka",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/slivka.png?raw=true",
        "ANIMAL"),
        new Beast("Targro",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/targro.png?raw=true",
        "ANIMAL"),
        new Beast("Komodo",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/komodo.png?raw=true",
        "ANIMAL"),
        new Beast("Luna",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/luna.png?raw=true",
        "ANIMAL"),
        new Beast("Madara",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/madara.png?raw=true",
        "ANIMAL"),
        new Beast("Muro",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/muro.png?raw=true",
        "ANIMAL"),
        new Beast("Equinos",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/equinos.png?raw=true",
        "ANIMAL"),
        new Beast("Kajin",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/kajin.png?raw=true",
        "ANIMAL"),
        new Beast("Kama",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/kama.png?raw=true",
        "ANIMAL"),
        new Beast("Aldroim",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/aldroim.png?raw=true",
        "ANIMAL"),
        new Beast("Arachnid",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/arachnid.png?raw=true",
        "ANIMAL"),
        new Beast("Claw",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/claw.png?raw=true",
        "ANIMAL"),
        new Beast("Convol",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/convol.png?raw=true",
        "ANIMAL")
    ]
}

function allBeasts() {
    return [
        new Beast("Cornix",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/cornix.png?raw=true",
        "FIRE"),
        new Beast("Doomskull",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/doomskull.png?raw=true",
        "FIRE"),   
        new Beast("Epos",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/epos.png?raw=true",
        "FIRE"),    
        new Beast("Ferno",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/ferno.png?raw=true",
        "FIRE"), 
        new Beast("Flaymar",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/flaymar.png?raw=true",
        "FIRE"),
        new Beast("Hellion",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/hellion.png?raw=true",
        "FIRE"),
        new Beast("Koba",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/koba.png?raw=true",
        "FIRE"),    
        new Beast("Murk",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/murk.png?raw=true",
        "FIRE"),
        new Beast("Elko",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/elko.png?raw=true",
        "WATER"),
        new Beast("Nixa",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/nixa.png?raw=true",
        "WATER"),
        new Beast("Ellik",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/ellik.png?raw=true",
        "WATER"),
        new Beast("Blaze",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/blaze.png?raw=true",
        "WATER"),
        new Beast("Marlik",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/marlik.png?raw=true",
        "WATER"),
        new Beast("Soara",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/soara.png?raw=true",
        "WATER"),
        new Beast("Plexor",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/plexor.png?raw=true",
        "WATER"),
        new Beast("Voltrex",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/voltrex.png?raw=true",
        "WATER"),  
        new Beast("Lustor",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/lustor.png?raw=true",
        "WATER"),
        new Beast("Sepron",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/sepron.png?raw=true",
        "WATER"),
        new Beast("Hecton",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/hecton.png?raw=true",
        "WATER"),
        new Beast("Krabb",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/krabb.png?raw=true",
        "WATER"),
        new Beast("Narga",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/narga.png?raw=true",
        "WATER"), 
        new Beast("Serpio",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/serpio.png?raw=true",
        "WATER"),
        new Beast("Balisk",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/balisk.png?raw=true",
        "WATER"),
        new Beast("Spikefin",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/spikefin.png?raw=true",
        "WATER"),
        new Beast("Amictus",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/amictus.png?raw=true",
        "AIR"),        
        new Beast("Brutus",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/brutus.png?raw=true",
        "AIR"),
        new Beast("Carnivora",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/carnivora.png?raw=true",
        "AIR"),
        new Beast("Fang",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/fang.png?raw=true",
        "AIR"),    
        new Beast("Falra",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/falra.png?raw=true",
        "AIR"), 
        new Beast("Linka",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/linka.png?raw=true",
        "AIR"),  
        new Beast("Hawkite",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/hawkite.png?raw=true",
        "AIR"),
        new Beast("Koraka",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/koraka.png?raw=true",
        "AIR"),
        new Beast("Kronus",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/kronus.png?raw=true",
        "AIR"),
        new Beast("Soltra",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/soltra.png?raw=true",
        "AIR"),
        new Beast("Torno",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/torno.png?raw=true",
        "AIR"),
        new Beast("Vespick",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/vespick.png?raw=true",
        "AIR"),
        new Beast("Tempest",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/tempest.png?raw=true",
        "AIR"),
        new Beast("Spark",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/spark.png?raw=true",
        "AIR"),
        new Beast("Oradu's Falcon",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/oradu'sfalcon.png?raw=true",
        "AIR"),
        new Beast("Arcta",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/arcta.png?raw=true",
        "EARTH"),
        new Beast("Kaymon",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/kaymon.png?raw=true",
        "EARTH"),
        new Beast("Krestor",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/krestor.png?raw=true",
        "EARTH"),
        new Beast("Rashouk",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/rashouk.png?raw=true",
        "EARTH"),
        new Beast("Koldo",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/koldo.png?raw=true",
        "EARTH"),
        new Beast("Nanook",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/nanook.png?raw=true",
        "EARTH"),
        new Beast("Rokk",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/rokk.png?raw=true",
        "EARTH"),
        new Beast("Solix",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/solix.png?raw=true",
        "EARTH"),
        new Beast("Sting",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/sting.png?raw=true",
        "EARTH"), 
        new Beast("Tarrok",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/tarrok.png?raw=true",
        "EARTH"),
        new Beast("Tecton",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/tecton.png?raw=true",
        "EARTH"),
        new Beast("Terra",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/terra.png?raw=true",
        "EARTH"),
        new Beast("Trema",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/trema.png?raw=true",
        "EARTH"),
        new Beast("Xerik",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/xerik.png?raw=true",
        "EARTH"),
        new Beast("Piranha Pirate",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/piranhapirate.png?raw=true",
        "EARTH"),
        new Beast("Malvel",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/malvel.png?raw=true",
        "WIZARD"),
        new Beast("Kensa",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/kensa.png?raw=true",
        "WIZARD"),
        new Beast("Aduro",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/aduro.png?raw=true",
        "WIZARD"),
        new Beast("Vermock",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/vermock.png?raw=true",
        "ANIMAL"),
        new Beast("Klaxa",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/klaxa.png?raw=true",
        "ANIMAL"),
        new Beast("Tauron",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/tauron.png?raw=true",
        "ANIMAL"),
        new Beast("Torgor",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/torgor.png?raw=true",
        "ANIMAL"),
        new Beast("Torpix",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/torpix.png?raw=true",
        "ANIMAL"),
        new Beast("Trillion",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/trillion.png?raw=true",
        "ANIMAL"),
        new Beast("Skor",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/skor.png?raw=true",
        "ANIMAL"),
        new Beast("Slivka",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/slivka.png?raw=true",
        "ANIMAL"),
        new Beast("Targro",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/targro.png?raw=true",
        "ANIMAL"),
        new Beast("Komodo",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/komodo.png?raw=true",
        "ANIMAL"),
        new Beast("Luna",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/luna.png?raw=true",
        "ANIMAL"),
        new Beast("Madara",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/madara.png?raw=true",
        "ANIMAL"),
        new Beast("Muro",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/muro.png?raw=true",
        "ANIMAL"),
        new Beast("Equinos",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/equinos.png?raw=true",
        "ANIMAL"),
        new Beast("Kajin",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/kajin.png?raw=true",
        "ANIMAL"),
        new Beast("Kama",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/kama.png?raw=true",
        "ANIMAL"),
        new Beast("Aldroim",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/aldroim.png?raw=true",
        "ANIMAL"),
        new Beast("Arachnid",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/arachnid.png?raw=true",
        "ANIMAL"),
        new Beast("Claw",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/claw.png?raw=true",
        "ANIMAL"),
        new Beast("Convol",
        "https://github.com/LyshaJaufar/BeastBattleInfo/blob/master/assets/beasts/convol.png?raw=true",
        "ANIMAL")  
    ]                                                                                                                                                                                                                                                                                                                                                                                                
}